[package]
name = "rust-game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tcod = "0.13"
noise = "0.7.0"
rand = "0.8.5"
hashbrown = "0.12"
specs = "0.17.0"
emerald = "0.2.0"